### ISSUE TITLE
depth image

### ISSUE THREAD

**Issue by antimodular** [antoniomechas/ofxWaterRipple#1]
hi.
this is a great addon. thanks for making it.

i am trying to use it to create a depth map of just greyscale values that i can use to map on to a mesh.
my ultimate goal is to have an ofMesh that moves according to your wave ripples.

just feeding your code a a black image obviously does not work.
how would i be able to get an image like this out of the code:

![grayscale_circle_tunnel_by_10binary-d4qq3eb](https://cloud.githubusercontent.com/assets/3649364/13036376/beb46dfe-d333-11e5-95a5-d44c0ef5a2ba.png)

thanks

**Comment by antoniomechas** [comment]
Hello,
You can get the depth from the texture that stores the values of the ripples.
To draw it, I have added a shader called drawDepth.frag to the example, just replace draw.frag by drawDepth.frag and you will get the drawing of the depth as a grayscale image.

**Comment by antimodular** [comment]
thanks so much.
